# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glimpse-project/glimpse/glab/ui/glab_wizard.ui'
#
# Created: Fri Nov  9 21:45:15 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.setWindowModality(QtCore.Qt.WindowModal)
        Wizard.resize(458, 300)
        Wizard.setWizardStyle(QtGui.QWizard.NStyles)
        self.param_page = QtGui.QWizardPage()
        self.param_page.setObjectName("param_page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.param_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.param_group_box = QtGui.QGroupBox(self.param_page)
        self.param_group_box.setObjectName("param_group_box")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.param_group_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.param_group_box)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.params = QtGui.QWidget()
        self.params.setGeometry(QtCore.QRect(0, 0, 394, 193))
        self.params.setObjectName("params")
        self.scrollArea.setWidget(self.params)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.param_group_box)
        Wizard.addPage(self.param_page)
        self.feature_page = QtGui.QWizardPage()
        self.feature_page.setObjectName("feature_page")
        self.verticalLayout = QtGui.QVBoxLayout(self.feature_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtGui.QGroupBox(self.feature_page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.feature_type = QtGui.QComboBox(self.groupBox_2)
        self.feature_type.setEditable(False)
        self.feature_type.setObjectName("feature_type")
        self.feature_type.addItem("")
        self.feature_type.addItem("")
        self.feature_type.addItem("")
        self.feature_type.addItem("")
        self.feature_type.addItem("")
        self.horizontalLayout_4.addWidget(self.feature_type)
        self.verticalLayout.addWidget(self.groupBox_2)
        Wizard.addPage(self.feature_page)
        self.proto_page = QtGui.QWizardPage()
        self.proto_page.setObjectName("proto_page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.proto_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtGui.QGroupBox(self.proto_page)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.proto_source = QtGui.QComboBox(self.groupBox_3)
        self.proto_source.setObjectName("proto_source")
        self.proto_source.addItem("")
        self.proto_source.addItem("")
        self.proto_source.addItem("")
        self.verticalLayout_6.addWidget(self.proto_source)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.proto_file_group = QtGui.QGroupBox(self.proto_page)
        self.proto_file_group.setObjectName("proto_file_group")
        self.gridLayout = QtGui.QGridLayout(self.proto_file_group)
        self.gridLayout.setObjectName("gridLayout")
        self.proto_file_lbl = QtGui.QLabel(self.proto_file_group)
        self.proto_file_lbl.setObjectName("proto_file_lbl")
        self.gridLayout.addWidget(self.proto_file_lbl, 0, 0, 1, 1)
        self.proto_file_btn = QtGui.QPushButton(self.proto_file_group)
        self.proto_file_btn.setMaximumSize(QtCore.QSize(149, 16777215))
        self.proto_file_btn.setObjectName("proto_file_btn")
        self.gridLayout.addWidget(self.proto_file_btn, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.proto_file_group)
        Wizard.addPage(self.proto_page)
        self.corpus_page = QtGui.QWizardPage()
        self.corpus_page.setObjectName("corpus_page")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.corpus_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtGui.QGroupBox(self.corpus_page)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.corpus_lbl = QtGui.QLabel(self.groupBox_4)
        self.corpus_lbl.setScaledContents(True)
        self.corpus_lbl.setObjectName("corpus_lbl")
        self.verticalLayout_10.addWidget(self.corpus_lbl)
        self.corpus_btn = QtGui.QPushButton(self.groupBox_4)
        self.corpus_btn.setMaximumSize(QtCore.QSize(149, 16777215))
        self.corpus_btn.setObjectName("corpus_btn")
        self.verticalLayout_10.addWidget(self.corpus_btn)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_7 = QtGui.QGroupBox(self.corpus_page)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.corpus_type = QtGui.QLabel(self.groupBox_7)
        self.corpus_type.setMinimumSize(QtCore.QSize(0, 40))
        self.corpus_type.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.corpus_type.setWordWrap(True)
        self.corpus_type.setObjectName("corpus_type")
        self.verticalLayout_5.addWidget(self.corpus_type)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        Wizard.addPage(self.corpus_page)
        self.eval_page = QtGui.QWizardPage()
        self.eval_page.setObjectName("eval_page")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.eval_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtGui.QGroupBox(self.eval_page)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.eval_criteria = QtGui.QComboBox(self.groupBox_5)
        self.eval_criteria.setObjectName("eval_criteria")
        self.eval_criteria.addItem("")
        self.eval_criteria.addItem("")
        self.verticalLayout_8.addWidget(self.eval_criteria)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_8 = QtGui.QGroupBox(self.eval_page)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.perf_measure = QtGui.QComboBox(self.groupBox_8)
        self.perf_measure.setObjectName("perf_measure")
        self.perf_measure.addItem("")
        self.perf_measure.addItem("")
        self.verticalLayout_9.addWidget(self.perf_measure)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        Wizard.addPage(self.eval_page)
        self.debug_page = QtGui.QWizardPage()
        self.debug_page.setObjectName("debug_page")
        self.horizontalLayout = QtGui.QHBoxLayout(self.debug_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.debug = QtGui.QTextEdit(self.debug_page)
        self.debug.setEnabled(True)
        self.debug.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.debug.setReadOnly(True)
        self.debug.setObjectName("debug")
        self.horizontalLayout.addWidget(self.debug)
        Wizard.addPage(self.debug_page)
        self.confirm_page = QtGui.QWizardPage()
        self.confirm_page.setObjectName("confirm_page")
        self.formLayout = QtGui.QFormLayout(self.confirm_page)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.confirm_page)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        Wizard.addPage(self.confirm_page)
        self.run_page = QtGui.QWizardPage()
        self.run_page.setObjectName("run_page")
        self.gridLayout_2 = QtGui.QGridLayout(self.run_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_6 = QtGui.QGroupBox(self.run_page)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem)
        self.progress_bar = QtGui.QProgressBar(self.groupBox_6)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_12.addWidget(self.progress_bar)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 0, 1, 1)
        Wizard.addPage(self.run_page)
        self.results_page = QtGui.QWizardPage()
        self.results_page.setObjectName("results_page")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.results_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtGui.QGroupBox(self.results_page)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11.addWidget(self.groupBox)
        Wizard.addPage(self.results_page)

        self.retranslateUi(Wizard)
        self.feature_type.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(QtGui.QApplication.translate("Wizard", "Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.param_group_box.setTitle(QtGui.QApplication.translate("Wizard", "Model Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Wizard", "Model Layer for Features", None, QtGui.QApplication.UnicodeUTF8))
        self.feature_type.setItemText(0, QtGui.QApplication.translate("Wizard", "Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.feature_type.setItemText(1, QtGui.QApplication.translate("Wizard", "S1", None, QtGui.QApplication.UnicodeUTF8))
        self.feature_type.setItemText(2, QtGui.QApplication.translate("Wizard", "C1", None, QtGui.QApplication.UnicodeUTF8))
        self.feature_type.setItemText(3, QtGui.QApplication.translate("Wizard", "S2", None, QtGui.QApplication.UnicodeUTF8))
        self.feature_type.setItemText(4, QtGui.QApplication.translate("Wizard", "C2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Wizard", "Source of S2 Prototypes", None, QtGui.QApplication.UnicodeUTF8))
        self.proto_source.setItemText(0, QtGui.QApplication.translate("Wizard", "Imprinted", None, QtGui.QApplication.UnicodeUTF8))
        self.proto_source.setItemText(1, QtGui.QApplication.translate("Wizard", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.proto_source.setItemText(2, QtGui.QApplication.translate("Wizard", "From File", None, QtGui.QApplication.UnicodeUTF8))
        self.proto_file_group.setTitle(QtGui.QApplication.translate("Wizard", "Prototype File", None, QtGui.QApplication.UnicodeUTF8))
        self.proto_file_lbl.setText(QtGui.QApplication.translate("Wizard", "(path)", None, QtGui.QApplication.UnicodeUTF8))
        self.proto_file_btn.setText(QtGui.QApplication.translate("Wizard", "Choose File", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Wizard", "Image Corpus", None, QtGui.QApplication.UnicodeUTF8))
        self.corpus_lbl.setText(QtGui.QApplication.translate("Wizard", "(path)", None, QtGui.QApplication.UnicodeUTF8))
        self.corpus_btn.setText(QtGui.QApplication.translate("Wizard", "Choose Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Wizard", "Corpus Type", None, QtGui.QApplication.UnicodeUTF8))
        self.corpus_type.setText(QtGui.QApplication.translate("Wizard", "(type)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Wizard", "Evaluation Method for Classification", None, QtGui.QApplication.UnicodeUTF8))
        self.eval_criteria.setItemText(0, QtGui.QApplication.translate("Wizard", "Fixed-Split", None, QtGui.QApplication.UnicodeUTF8))
        self.eval_criteria.setItemText(1, QtGui.QApplication.translate("Wizard", "Cross-Validation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Wizard", "Performance Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_measure.setItemText(0, QtGui.QApplication.translate("Wizard", "Accuracy", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_measure.setItemText(1, QtGui.QApplication.translate("Wizard", "AUC", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Wizard", "(show settings and confirm)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Wizard", "Running experiments", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Wizard", "Results", None, QtGui.QApplication.UnicodeUTF8))

