package:
  name: glimpse
  version: !!str 0.2.1

source:
  git_url: https://github.com/mthomure/glimpse-project.git
  git_tag: master

#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - glimpse = glimpse:main
    #
    # Would create an entry point called glimpse that calls glimpse.main()

    - glab = glimpse.glab.cli:Main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - decorator
    - ipython 2.1.0
    - numpy
    - setuptools
    - pil
    - python
    - pyzmq 14.3.0
    - scikit-learn 0.14.1
    - scipy
    - traits
    - traitsui

  run:
    - decorator
    - ipython 2.1.0
    - numpy
    - matplotlib
    - pil
    - python
    - pyzmq 14.3.0
    - scikit-learn 0.14.1
    - scipy
    - traits
    - traitsui

test:
  # Python imports
  imports:
    - glimpse
    - glimpse.backends
    - glimpse.corpora
    - glimpse.experiment
    - glimpse.glab
    - glimpse.glab.experiment
    - glimpse.glab.ui
    - glimpse.models
    - glimpse.models.base
    - glimpse.models.ml
    - glimpse.pools
    - glimpse.pools.ipythoncluster
    - glimpse.prototypes
    - glimpse.util
    - glimpse.util.dataflow
    - glimpse.util.gplot
    - glimpse.util.learn

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - glab

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mthomure/glimpse-project
  license: MIT License
  summary: 'Hierarchical visual models in C++ and Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
